## IMPORTANT: DO NOT EDIT THIS FILE ##

s, i, f, b, e = 'string', 'int', 'float', 'bool', 'error'
arithmetic_tests = [8, -33, 957, 24, 284]
type_tests = [s, s, i, s, s, f, s, i, f, f, i, i, e, b, b, b, b, s]