## IMPORTANT: DO NOT EDIT THIS FILE ##

import arithmetic_exercise as a
import types_exercise as t
import prints

not_done = True
while not_done:
  trying = input("Which file would you like to run?\n")
  not_done = False
  if trying == "arithmetic":
    a.main()
  elif trying == "prints":
    prints.self_intro()
  elif trying == "types":
    t.main()
  else:
    not_done = True
    print("Invalid file, please try again.")
